# Generated by Django 6.1 on 2026-08-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('taille', models.CharField(max_length=20)),
                ('couleur', models.CharField(max_length=50)),
                ('mesures', models.TextField(blank=True)),
                ('message', models.TextField(blank=True)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('traitee', models.BooleanField(default=False)),
                ('creation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='boutique.creation')),
            ],
        ),
    ]
