# Generated by Django 6.1 on 2026-08-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boutique', '0002_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='creation',
            name='categorie',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Enfant', 'Enfant'), ('Accessoire', 'Accessoire')], default='Femme', max_length=30),
        ),
    ]
